# this file has been moved! consume file at https://github.com/influxdata/openapi/blob/master/contracts/oss.yml
# continue to maintain and develop the definition at https://github.com/influxdata/openapi/blob/master/src/oss.yml
